### ISSUE TITLE
Direct Link to the Paper and Hashtags mentioning

### ISSUE THREAD

**Issue by nicolay-r** [nerel-ds/NEREL#2]
Repository has the `about` section which is not filled:

![image](https://user-images.githubusercontent.com/14871187/171353325-6bd0ea69-f8f2-4378-bdbc-91aefee36fc7.png)

The one who owns this repository could provide the following information:
1) Link to the paper
2) Provide hashtags and keywords

**Comment by nerel-ds** [comment]
Done
