### ISSUE TITLE
Link to Benchmark

### ISSUE THREAD

**Issue by imvladikon** [nerel-ds/NEREL#3]
A very interesting work, but it seems that the link https://github.com/nerel-ds/nested-ner-benchmarks is not available. Is nested benchmark available somewhere?
Thank you!

**Comment by nerel-ds** [comment]
Our article was under review, so we temporarily closed access to this repository due to the need for anonymity.  Now the link works.

**Comment by imvladikon** [comment]
It's working!
Thank you for your great work!
